"""
Replacing the work done in: b78a734006fc
Revision ID: 02_after_encrypt_20200413185403
Revises: e8648dab8e18
Create Date: 2020-04-13 18:54:03.000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '02_after_encrypt_20200413185403'
down_revision = '01_squashed_20200413143615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    op.alter_column('users', 'crypt', new_column_name='token',
                    existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType()
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # b78a734006fc # 3
    op.alter_column('users', 'token', new_column_name='crypt',
                    existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType()
                    )
    op.add_column('users', sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    # Then copy all values from crypt column to token column, but now not encrypted.
    # ### end Alembic commands ###
