"""empty message

Revision ID: 12b85a538f29
Revises: e8648dab8e18
Create Date: 2020-04-08 20:22:41.027257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12b85a538f29'
down_revision = 'e8648dab8e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'saved_media')
    op.add_column('posts', sa.Column('saved_media', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'saved_media')
    op.add_column('posts', sa.Column('saved_media', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True))
    # ### end Alembic commands ###
