"""empty message

Revision ID: 04_add_page_id
Revises: 03_fix_defaults
Create Date: 2020-04-17 22:14:16.712594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04_add_page_id'
down_revision = '03_fix_defaults'
branch_labels = ('track-fb-page',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('page_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('users', sa.Column('story_subscribed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['page_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'story_subscribed')
    op.drop_column('users', 'page_id')
    # ### end Alembic commands ###
