"""empty message

Revision ID: 05_add_page_token
Revises: 04_add_page_id
Create Date: 2020-04-20 03:24:02.884988

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '05_add_page_token'
down_revision = '04_add_page_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('page_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'page_token')
    # ### end Alembic commands ###
