"""empty message

Revision ID: 06_capture_queue
Revises: 05_add_page_token
Create Date: 2020-04-28 14:09:05.492908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06_capture_queue'
down_revision = '05_add_page_token'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('capture_name', sa.String(length=191), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'capture_name')
    # ### end Alembic commands ###
