"""empty message

Revision ID: 1f292a866062
Revises: 5e56967bead8
Create Date: 2020-03-14 06:22:45.454563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f292a866062'
down_revision = '5e56967bead8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temptest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temptest',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('info', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.Column('modified', mysql.DATETIME(), nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('moreinfo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
