"""empty message

Revision ID: 5e56967bead8
Revises: e25ad5d62018
Create Date: 2020-03-14 06:21:29.024595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e56967bead8'
down_revision = 'e25ad5d62018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temptest', sa.Column('moreinfo', sa.String(length=191), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temptest', 'moreinfo')
    # ### end Alembic commands ###
