"""empty message

Revision ID: 80421895c9c1
Revises: dca6e235628f
Create Date: 2020-03-17 05:37:28.299589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80421895c9c1'
down_revision = 'dca6e235628f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # DONE: Modify to table rename
    op.rename_table('rejected_campaigns', 'processed_campaigns')
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_1', 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.rename_table('processed_campaigns', 'rejected_campaigns')
    # op.create_table('rejected_campaigns',
    # sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    # sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    # sa.Column('campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='rejected_campaigns_ibfk_1', ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='rejected_campaigns_ibfk_2', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_unicode_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.drop_table('processed_campaigns')
    # ### end Alembic commands ###
