"""empty message

Revision ID: e25ad5d62018
Revises: 
Create Date: 2020-03-14 06:07:54.334182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25ad5d62018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temptest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=191), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temptest')
    # ### end Alembic commands ###
