"""empty message
Replacing: 12b85a538f29, e8648dab8e18, b78a734006fc, 5608765dc3c8, 80421895c9c1, dca6e235628f
Revision ID: squashed-20200413143615
Revises: e8648dab8e18
Create Date: 2020-04-13 14:36:15.000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'squashed-20200413143615'
down_revision = None
branch_labels = None
depends_on = None


def _dev_encrypt():
    """ Takes value in token field and saves in encrypt field, triggering the encryption process.
        Function is only for use by dev admin.
    """
    from .model_db import db, User
    from sqlalchemy_utils import EncryptedType  # encrypt
    from sqlalchemy_utils.types.encrypted.encrypted_type import AesEngine  # encrypt
    from cryptography.fernet import Fernet  # encrypt
    from os import environ

    SECRET_KEY = environ.get('SECRET_KEY')
    # op.add_column('users', sa.Column('crypt', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
    # crypt = db.Column(EncryptedType(db.String(255), SECRET_KEY, AesEngine, 'pkcs5'))  # encrypt
    # Which means the following?
    # op.add_column('users', sa.Column('crypt', EncryptedType(db.String(255), SECRET_KEY, AesEngine, 'pkcs5'), nullable=True))

    message, count = '', 0
    users = User.query.all()
    try:
        for user in users:
            value = getattr(user, 'token')
            setattr(user, 'crypt', value)
            count += 1
        message += f"Adjusted for {count} users. "
        db.session.commit()
        message += "Commit Finished! "
        success = True
    except Exception as e:
        success = False
        temp = f"Encrypt method error. Count: {count}. "
        print(temp)
        print(e)
        message += temp
        db.session.rollback()
    return message, success


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # dca6e235628f # 0
    op.create_table('post_campaigns',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('campaign_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('processed_campaigns',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('campaign_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.drop_column('posts', 'processed')
    op.drop_column('posts', 'campaign_id')
    # 80421895c9c1 # 1
    op.alter_column('posts', 'user_id', existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # 5608765dc3c8 # 2
    op.add_column('users', sa.Column('crypt', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
    # copy all contents from token to crypt, but now contents encrypted.
    # b78a734006fc # 3
    op.drop_column('users', 'token')
    op.alter_column('users', 'crypt', new_column_name='token',
                    existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType()
                    )
    # e8648dab8e18 # 4
    # op.add_column('posts', sa.Column('saved_media', sa.String(length=191), nullable=True))
    # 12b85a538f29 # 5
    # op.drop_column('posts', 'saved_media')
    op.add_column('posts', sa.Column('saved_media', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 12b85a538f29 # 5
    op.drop_column('posts', 'saved_media')
    # op.add_column('posts', sa.Column('saved_media', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True))
    # e8648dab8e18 # 4
    # op.drop_column('posts', 'saved_media')
    # b78a734006fc # 3
    op.alter_column('users', 'token', new_column_name='crypt',
                    existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType()
                    )
    op.add_column('users', sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    # copy all contents from crypt to token, but now contents NOT encrypted.
    # 5608765dc3c8 # 2
    op.drop_column('users', 'crypt')
    # 80421895c9c1 # 1
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_ibfk_1', 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'user_id', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    # dca6e235628f # 0
    op.add_column('posts', sa.Column('campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_ibfk_2', 'posts', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.drop_table('processed_campaigns')
    op.drop_table('post_campaigns')

    # ### end Alembic commands ###
